/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        room_no = new javax.swing.JTextField();
        room_type = new javax.swing.JComboBox<>();
        status1 = new javax.swing.JComboBox<>();
        bed_type = new javax.swing.JComboBox<>();
        price1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 130, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 130, 50));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Room No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Room Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 50, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Bed Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));

        room_no.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(room_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 250, 40));

        room_type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        room_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non Ac", "Super Delux", "VIP" }));
        getContentPane().add(room_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 250, 40));

        status1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        status1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available" }));
        getContentPane().add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 250, 40));

        bed_type.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bed_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        getContentPane().add(bed_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 250, 40));

        price1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 250, 40));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Availablity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 28, 50, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Status");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 70, -1));

        cStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clean", "Dirty" }));
        getContentPane().add(cStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 250, 40));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 115, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rooms.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
           
           room_no.setText("");
           price1.setText("");
           room_type.setSelectedIndex(-1);
           bed_type.setSelectedIndex(-1);
           status1.setSelectedIndex(-1);
           cStatus.setSelectedIndex(-1);
           
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       String rn=room_no.getText();
       String rt=room_type.getSelectedItem().toString();
       String bt=bed_type.getSelectedItem().toString();
       String price=price1.getText();
       String status=status1.getSelectedItem().toString();
       String cS=cStatus.getSelectedItem().toString();
       
       if(rn.isEmpty() || rt.isEmpty() || bt.isEmpty() || price.isEmpty() || status.isEmpty()||cS.isEmpty())
       {
       JOptionPane.showMessageDialog(null,"Fill Properly");
       }
      else
       {
       
       try 
        {
            //connection
           Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms_db?" + "user=root&password=");  
           
           String q11="select *  from room where room_no='"+rn+"'";
           PreparedStatement pst = conn.prepareStatement(q11);
           ResultSet rs11 = pst.executeQuery();
           if(rs11.next())
           {
               JOptionPane.showMessageDialog(null,"Already exist");
           }
           else
           {
            //Queries
            String q1="INSERT INTO room (room_no,room_type,bed,status,cleaning_status,price) VALUES ('"+rn+"','"+rt+"','"+bt+"','"+status+"','"+cS+"','"+price+"')";
            //Prepeared Statement
            PreparedStatement pst1=conn.prepareStatement(q1);
            //Execute(insert/delete/edit)
            pst1.executeUpdate();
            //save changes(commit)
           JOptionPane.showMessageDialog(null,"Successfully Inserted");
            //inserted 
           }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Something Went Wrong");
        }
       }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        AdminDash dash=new AdminDash();
        dash.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bed_type;
    private javax.swing.JComboBox<String> cStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField room_no;
    private javax.swing.JComboBox<String> room_type;
    private javax.swing.JComboBox<String> status1;
    // End of variables declaration//GEN-END:variables
}
